### ISSUE TITLE
Design data dictionary output format

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#199]
We need a data dictionary format that we can share with others and that our own tools can handle. This data dictionary should be [BIDS compatible](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) and has to be able to transform a raw `participants.tsv` into a harmonized representation.

For this it needs to have:

- links to controlled terms (IRIs)
- list of "missing" values that are typos or otherwise irrelevant (usually omitted in BIDS dictionaries)
- a way to explain that a column belongs to an assessment tool

Here is a first example of the data dictionary format based on a BIDS data dictionary:
```yaml
# Data dictionary schema draft
categorical:
  Description: "human readable description"
  Levels:
    level1: "human readable description"
    level2: "human readable description"
  Annotation:
    TermURL: "URI of controlled term"
    Label: "human readable label of term"
    Levels:
      level1: # The terms from above in Levels
        TermURL: "URI to a controlled vocabulary for this term"
        Label: "human readable label for the above term"
      level2:
        termURL: "URI to a controlled vocabulary for this term"
        label: "human readable label for the above term"
    MissingValues:
      - " "
      - ""

continuous:
  Description: "human readable description"
  Units: "unit name, possibly just human readable, but could probably be an xsd string"
  Annotation:
    IsAbout:
      TermURL: "URI of controlled term"
      Label: "human readable label of term"
    Unit:
      Identifier: "xsd:integer"
    Transformation:
      Identifier: "unique name of a well defined transformation"
      Description: "human readable description of the transformation"
    MissingValues:
      - ""
      - "99"

# Subscales that belong to a tool
subscale1:
  Description: "human readable description"
  IsPartOf:
    TermURL: "URI of the name of the tool"
    Label: "human readable label of term"
  MissingValues:
    - ""
    - "not present"


subscale2:
  Description: "human readable description"
  IsPartOf:
    TermURL: "URI of the name of the tool"
    Label: "human readable label of term"

```

Steps to complete:

- [x] document a draft of this on our docs
- [x] implement the schema in pydantic
- [x] create a jsonschema to validate with 
- [x] put this draft somewhere we can get feedback on it

Linked to #6
